<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>vs2022;vs2026_5</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>

    <TargetPlatformIdentifier>Windows</TargetPlatformIdentifier>
    <TargetPlatformVersion>7.0</TargetPlatformVersion>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworkIdentifier Condition=" '$(TargetFramework)' == 'vs2026_5' ">.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion Condition=" '$(TargetFramework)' == 'vs2026_5' ">v10.0</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworkIdentifier Condition=" '$(TargetFramework)' == 'vs2022' ">.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion Condition=" '$(TargetFramework)' == 'vs2022' ">v8.0</TargetFrameworkVersion>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Lib2\Lib2.csproj" />
    <ProjectReference Include="..\Lib3\Lib3.csproj" />
    <ProjectReference Include="..\Lib4\Lib4.csproj" />
  </ItemGroup>

</Project>