<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>apple;banana</TargetFrameworks>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <SdkAnalysisLevel>10.0.300</SdkAnalysisLevel>
  </PropertyGroup>

  <PropertyGroup>
    <!-- <IncludeBuildOutput Condition=" '$(TargetFramework)' == 'apple' ">false</IncludeBuildOutput> -->
    <SuppressDependenciesWhenPacking Condition=" '$(TargetFramework)' == 'banana' ">true</SuppressDependenciesWhenPacking>
    <TargetFrameworkIdentifier Condition=" '$(TargetFramework)' == 'apple' ">.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion Condition=" '$(TargetFramework)' == 'apple' ">v10.0</TargetFrameworkVersion>
  </PropertyGroup>
  <PropertyGroup>
    <TargetFrameworkIdentifier Condition=" '$(TargetFramework)' == 'banana' ">.NETCoreApp</TargetFrameworkIdentifier>
    <TargetFrameworkVersion Condition=" '$(TargetFramework)' == 'banana' ">v10.0</TargetFrameworkVersion>
  </PropertyGroup>


  <ItemGroup>
    <Content Include="Content.md" Condition=" '$(TargetFramework)' == 'banana' "/>
    <PackageReference Include="NuGet.Common" Version="7.3.0" />
    <PackageReference Include="NuGet.Versioning" Version="7.3.0" Condition=" '$(TargetFramework)' == 'apple' "/>
    <ProjectReference Include="../Lib2/Lib2.csproj" Condition=" '$(TargetFramework)' == 'banana' "/>
  </ItemGroup>

</Project>